### ISSUE TITLE
Device not found 

### ISSUE THREAD

**Issue by devgnrb** [gryf/linak-ctrl#1]
I've got "Device 4819:0002 not found!" but I've got a USB2LIN06 plugged in usb. 
I've got the pyusb installed (V1.2.1) with python 3.10.7 and whenever I'm trying to run your __init__.py file, I've got this error :/ 

Do you have any idea ? 

This package is working: https://github.com/monofox/python-linak-desk-control 
but this is not perfect so I wanted to try yours. 
Thanks !

**Comment by gryf** [comment]
Can you post output of command `lsusb`?

**Comment by devgnrb** [comment]
Finally, I fixed with the dev this package so I don't use yours and I switched project now sorry 
 https://github.com/monofox/python-linak-desk-control

**Comment by gryf** [comment]
Ok, no worries. And since I'm not able to reproduce your issue, I'm closing it now.
